export default {
  ET_DATA: [
    { LINE: 'UJ0_PARAM' },
    { LINE: 'UJ0_PARAM_APPT' },
    { LINE: 'UJ0_PARAMT' },
    { LINE: 'UJ0_PARAM_APP' },
    { LINE: 'UJ0_PLAN' },
    { LINE: 'UJ0_PLANT' },
    { LINE: 'UJ0_PLAN_LOG' },
    { LINE: 'UJ0_SCHEDULE' },  
    { LINE: 'UJA_DIM_APPL' },
    { LINE: 'UJA_APPL' },
    { LINE: 'UJA_APPLT' },
    { LINE: 'UJA_APPSETT' },
    { LINE: 'UJA_APPSET_INFO' },
    { LINE: 'UJA_DIMENSION' },
    { LINE: 'UJA_DIMENSIONT' },
    { LINE: 'UJF_DOC' },
    { LINE: 'UJF_DOCTREE' },
    { LINE: 'UJD_INSTRUCTION' },
    { LINE: 'UJD_PACKAGES' },
    { LINE: 'UJD_SCHEDULET' },
    { LINE: 'UJD_LINK' },
    { LINE: 'UJD_LINK_LOG' },
    { LINE: 'UJD_PACKAGE_LINK' },
    { LINE: 'UJD_PACKAGE_PLAN' },
    { LINE: 'UJD_PK_PLAN_MAP' },
    { LINE: 'UJD_PLINK_LOG' },
    { LINE: 'UJD_PLINK_PLAN' },
    { LINE: 'UJD_PLK_PLAN_MAP' },
    { LINE: 'UJD_STATUS' },
    { LINE: 'UJD_INSTRUCTION2' },
    { LINE: 'UJD_PACKAGES2' },
    { LINE: 'UJD_PACKAGEST2' },
    { LINE: 'UJD_PACKAGEST' },
    { LINE: 'UJD_SCHEDULE' },
  ],
  DELIMITER: ';',
  NO_DATA: '',
  QUERY_TABLE: 'DD02L',
  ROWCOUNT: 999999,
  ROWSKIPS: 0,
  USE_ET_DATA_4_RETURN: 'X',
  FIELDS: [
    {
      FIELDNAME: 'TABNAME',
      OFFSET: '000000',
      LENGTH: '000030',
      TYPE: 'C',
      FIELDTEXT: '',
    },
  ],
  OPTIONS: [{ TEXT: "TABCLASS EQ 'TRANSP'" }],
};
