export default {
  ET_DATA: [
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Clear' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Copy' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Export Master Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Export Transaction Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Description' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Load Transaction Data from BW InfoProvider' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Load Transaction Data from BW InfoProvider UI' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Move' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Clear' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Copy' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Export Master Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Export Transaction Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Description' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Load Transaction Data from BW InfoProvider' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Load Transaction Data from BW InfoProvider UI' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Move' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Clear' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Copy' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Export Master Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Export Transaction Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Description' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Load Transaction Data from BW InfoProvider' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Load Transaction Data from BW InfoProvider UI' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Move' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Clear' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Copy' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Load Transaction Data from BW InfoProvider' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Load Transaction Data from BW InfoProvider UI' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Move' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Export Master Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Export Transaction Data to File' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Description' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Inter Company Booking' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Inter Company Data' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Inter Company Elimination' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Legal Consolidation' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Openning Balances' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Account Transformation' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Allocation' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;FX Restatement' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Financial Process;Validations' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Append' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Transaction Data Last Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Transaction Data Aggregate Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Master Data Hierarchies InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Master Data Attrib and Text InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Master Data Attrib and Hier Flat File' },
    { LINE: 'ENVIRONMENTSHELL;Consolidation;;Data Management;Import Transaction Data Last Overwrite Mode FTP' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Financial Process;Ownership Calculation' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Append' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Transaction Data Last Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Transaction Data Aggregate Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Master Data Hierarchies InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Master Data Attrib and Text InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Master Data Attrib and Hier Flat File' },
    { LINE: 'ENVIRONMENTSHELL;Ownership;;Data Management;Import Transaction Data Last Overwrite Mode FTP' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Append' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Transaction Data Last Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Transaction Data Aggregate Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Master Data Hierarchies InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Master Data Attrib and Text InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Master Data Attrib and Hier Flat File' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Data Management;Import Transaction Data Last Overwrite Mode FTP' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Financial Process;Allocation' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Financial Process;FX Restatement' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Financial Process;Validations' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Other Function;Archive Data' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Other Function;Full Optimize' },
    { LINE: 'ENVIRONMENTSHELL;Planning;;Other Function;Lite Optimize' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Append' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Master Data Attrib and Hier Flat File' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Transaction Data Last Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Transaction Data Aggregate Overwrite Mode' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Master Data Hierarchies InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Master Data Attrib and Text InfoObj' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Data Management;Import Transaction Data Last Overwrite Mode FTP' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Other Function;Archive Data' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Other Function;Full Optimize' },
    { LINE: 'ENVIRONMENTSHELL;Rates;;Other Function;Lite Optimize' },
  ],
  DELIMITER: ';',
  GET_SORTED: '',
  NO_DATA: '',
  QUERY_TABLE: 'UJD_PACKAGES2',
  ROWCOUNT: 999999,
  ROWSKIPS: 0,
  USE_ET_DATA_4_RETURN: 'X',
  FIELDS: [
    {
      FIELDNAME: 'APPSET_ID',
      OFFSET: '000000',
      LENGTH: '000020',
      TYPE: 'C',
      FIELDTEXT: '',
    },
    {
      FIELDNAME: 'APP_ID',
      OFFSET: '000021',
      LENGTH: '000020',
      TYPE: 'C',
      FIELDTEXT: '',
    },
    {
      FIELDNAME: 'TEAM_ID',
      OFFSET: '000042',
      LENGTH: '000020',
      TYPE: 'C',
      FIELDTEXT: '',
    },
    {
      FIELDNAME: 'GROUP_ID',
      OFFSET: '000063',
      LENGTH: '000050',
      TYPE: 'C',
      FIELDTEXT: '',
    },
    {
      FIELDNAME: 'PACKAGE_ID',
      OFFSET: '000114',
      LENGTH: '000050',
      TYPE: 'C',
      FIELDTEXT: '',
    },
  ],
  OPTIONS: [{ TEXT: "PACKAGE_ID NE ''" }],
};
