export default 
{
  ET_DATA: [
    {
      LINE: '00O2TIYL35HT0WUCNR3KJDFO7;<?xml version="1.0" encoding="utf-16"?>\n' +
        '<UJD_S_RUN_PACKAGE_PARA><APPSET_ID>ENVIRONMENTSHELL</APPSET_ID><APPL_ID>Consolidation</APPL_ID><USER_ID>SAP_USER</USER_ID><IP_ADDR></IP_ADDR><SESSION_ID></SESSION_ID><LANGU>E</LANGU><MACHINE_NAME></MACHINE_NAME><TEAM_ID></TEAM_ID><GROUP_ID>System Administrative</GROUP_ID><PACKAGE_ID>Load Transaction Data from BW InfoProvider</PACKAGE_ID><ANSWER_PROMPT></ANSWER_PROMPT><IF_CHAIN></IF_CHAIN><CHAIN_ID>/CPMB/LOAD_INFOPROV</CHAIN_ID><PKUR_TYPE>2</PKUR_TYPE></UJD_S_RUN_PACKAGE_PARA>;1;00O2TIYL35HT0WUCNR3KJDLZR'
    },
    {
      LINE: '00O2TIYL35HRE6ZRUEF29QEAG;<?xml version="1.0" encoding="utf-16"?>\n' +
        '<UJD_S_RUN_PACKAGE_PARA><APPSET_ID>ENVIRONMENTSHELL</APPSET_ID><APPL_ID>Planning</APPL_ID><USER_ID>SAP_USER</USER_ID><IP_ADDR></IP_ADDR><SESSION_ID></SESSION_ID><LANGU>E</LANGU><MACHINE_NAME></MACHINE_NAME><TEAM_ID></TEAM_ID><GROUP_ID>System Administrative</GROUP_ID><PACKAGE_ID>Load Transaction Data from BW InfoProvider</PACKAGE_ID><ANSWER_PROMPT></ANSWER_PROMPT><IF_CHAIN></IF_CHAIN><CHAIN_ID>/CPMB/LOAD_INFOPROV</CHAIN_ID><PKUR_TYPE>2</PKUR_TYPE></UJD_S_RUN_PACKAGE_PARA>;1;00O2TIYL35HRE6ZRUEF29QKM0'
    }
  ],
  DELIMITER: ';',
  GET_SORTED: '',
  NO_DATA: '',
  QUERY_TABLE: 'UJ0_PLAN',
  ROWCOUNT: 10000,
  ROWSKIPS: 0,
  USE_ET_DATA_4_RETURN: 'X',
  DATA: [],
  FIELDS: [
    {
      FIELDNAME: 'PLAN_ID',
      OFFSET: '000000',
      LENGTH: '000025',
      TYPE: 'C',
      FIELDTEXT: ''
    },
    {
      FIELDNAME: 'PLAN_PARA',
      OFFSET: '000000',
      LENGTH: '000000',
      TYPE: 'g',
      FIELDTEXT: ''
    },
    {
      FIELDNAME: 'PLAN_STATUS',
      OFFSET: '000027',
      LENGTH: '000001',
      TYPE: 'C',
      FIELDTEXT: ''
    },
    {
      FIELDNAME: 'SCHEDULE_ID',
      OFFSET: '000029',
      LENGTH: '000025',
      TYPE: 'C',
      FIELDTEXT: ''
    }
  ],
  OPTIONS: [
    { TEXT: 'PLAN_STATUS IN (0,1)' },
    { TEXT: " AND EXECUTE_CLASS EQ 'CL_UJD_EXECUTE_PACKAGE_TASK'" }
  ]
}